apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: demo
spec:
  storageClassName: manual2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-redis
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo
        tier: redis
    spec:
      containers:
      - image: stellarhub/redisbuild:latest
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
