kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  clusterIP: None
  ports:
  - port: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: db
subsets:
  - addresses:
        - ip: 192.168.38.49
    ports:
      - port: 3306
        name: db
